# Generated by Django 4.1 on 2022-08-12 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
